def start():
	print('''  
      __^__                                      __^__
     ( ___ )------------------------------------( ___ )
      | / |                                      | \ |
      | / |   Welcome to the Python Algorithms   | \ |
      |___|           by Alejandoing             |___|
     (_____)------------------------------------(_____) 
    ''')

	print('''Please, select a option to get started: 
		[01] - Cryptography
		[02] - Coming soon...
		[03] - Coming soon...
		[04] - Coming soon...
		[05] - Coming soon...
		[06] - Coming soon...
		[07] - Coming soon...
		[08] - Coming soon...
		[09] - Coming soon...
		[10] - Coming soon...
		[11] - Coming soon...
		[12] - Coming soon...
		[13] - Coming soon...
		[14] - Coming soon...
		[15] - Coming soon...
		[16] - Coming soon...
		[17] - Coming soon...
		[18] - Coming soon...
		[19] - Coming soon...
		[20] - Coming soon...
	''')
	
	try:
		option = int(input('Your option: '))
		print('You have chosen the option {}'.format(option))
	except:
		print('No letters or special characters are permitted')

if __name__ == '__main__':
	start()