import cryptography

def start():
	print('''  
      __^__                                      __^__
     ( ___ )------------------------------------( ___ )
      | / |                                      | \ |
      | / |   Welcome to the Python Algorithms   | \ |
      |___|           by Alejandoing             |___|
     (_____)------------------------------------(_____) 
    ''')

	print('''Please, select a option to get started: 
		[1] - Cryptography
		[2] - Coming soon...
		[3] - Coming soon...
		[4] - Coming soon...
		[5] - Coming soon...
		[6] - Coming soon...
		[7] - Coming soon...
		[8] - Coming soon...
		[9] - Coming soon...
		[10] - Coming soon...
		[11] - Coming soon...
		[12] - Coming soon...
		[13] - Coming soon...
		[14] - Coming soon...
		[15] - Coming soon...
		[16] - Coming soon...
		[17] - Coming soon...
		[18] - Coming soon...
		[19] - Coming soon...
		[20] - Coming soon...
	''')
	
	try:
		option = int(input('Your option: '))
		print('You have chosen the option {}'.format(option))
		run_program(option)
		return True
	except ValueError: 
		print('No letters or special characters are permitted')
		return False

def run_program(option):
	programs = { 1: cryptography }
	return programs[option].start()
	
if __name__ == '__main__':
	start()